// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9zoDlU8UaO9K1Mf4kDwhaJn2rxokB4r0',
    appId: '1:286092341651:web:53b499382da14644faf866',
    messagingSenderId: '286092341651',
    projectId: 'notlocal-kzrpui',
    authDomain: 'notlocal-kzrpui.firebaseapp.com',
    storageBucket: 'notlocal-kzrpui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRDGrOMKBGRNfmFYx4aMlGXvHKqdfakk',
    appId: '1:286092341651:android:7846b6e9f2d5616efaf866',
    messagingSenderId: '286092341651',
    projectId: 'notlocal-kzrpui',
    storageBucket: 'notlocal-kzrpui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJIXljr49T4lXq1ReVsBqeBCivegqpJQ',
    appId: '1:286092341651:ios:be03c190a0d7a4d1faf866',
    messagingSenderId: '286092341651',
    projectId: 'notlocal-kzrpui',
    storageBucket: 'notlocal-kzrpui.appspot.com',
    iosClientId: '286092341651-5jvehh4kjkn59opt7sdhl0hjdghgi33m.apps.googleusercontent.com',
    iosBundleId: 'com.example.presetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJIXljr49T4lXq1ReVsBqeBCivegqpJQ',
    appId: '1:286092341651:ios:d44b990532969d9bfaf866',
    messagingSenderId: '286092341651',
    projectId: 'notlocal-kzrpui',
    storageBucket: 'notlocal-kzrpui.appspot.com',
    iosClientId: '286092341651-0t5sfsijv3n5rgt0tloq8vav1fd0gur4.apps.googleusercontent.com',
    iosBundleId: 'friends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9zoDlU8UaO9K1Mf4kDwhaJn2rxokB4r0',
    appId: '1:286092341651:web:53b499382da14644faf866',
    messagingSenderId: '286092341651',
    projectId: 'notlocal-kzrpui',
    authDomain: 'notlocal-kzrpui.firebaseapp.com',
    storageBucket: 'notlocal-kzrpui.appspot.com',
  );
}
